Project completed and apply for checkup
GzimAsani/Microverse-first-html-project pull request #2
Opened 2020-08-17 09:22 UTC by GzimAsani

We have completed the project and its requirements and now we are submitting it for a review.

2020-08-17 17:17 UTC, krys2fa requested changes
## Awesome work @GzimAsani and @Rayan84 👏 
Your project displays good use of CSS classes and GitHub Flow. 💪 

Just a few more adjustments to improve and complete the project. Please find them listed below.
### Status: Changes Required ♻️ 

- [x] [REQUIRED] The Pull Request should have a meaningful title. Something like in the image below.
![Screen Shot 2020-07-09 at 4 37 08 PM](https://user-images.githubusercontent.com/18187039/90422808-e9cfe700-e0aa-11ea-923f-05e7c710572e.png)

- [x] [REQUIRED] The search icon is not positioned correctly in the search input. This is what your page shows:
![Screen Shot 2020-08-17 at 5 04 52 PM](https://user-images.githubusercontent.com/18187039/90423405-ea1cb200-e0ab-11ea-8e82-caab1c6a2486.png)

- [x] [REQUIRED] The `Up Next` title and `Autoplay` icons are missing in your side bar.
This is what is present in the original:
<img width="382" alt="Screen Shot 2020-08-17 at 5 10 39 PM" src="https://user-images.githubusercontent.com/18187039/90423796-a2e2f100-e0ac-11ea-8d84-02d1846d4c31.png"> 

- [x] [REQUIRED ] The footer is missing from your page. It should look like this:
<img width="993" alt="Screen Shot 2020-08-17 at 5 13 37 PM" src="https://user-images.githubusercontent.com/18187039/90424118-1edd3900-e0ad-11ea-9381-7f11e210e1ff.png">

- [x] [REQUIRED]  Your project should match the appearance of [this archived youtube video player page. ](http://archive.vn/Bss88)

**NB:** The web page was reviewed at a screen size of **1440px.** Kindly state the screen size the project was built at if the page displays better at that size.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-08-17 17:17 UTC, krys2fa commented on README.md
> +<img src='./media/screenshot.png'>
- [x] [REQUIRED] Please change this image to a more suitable one. The texts in the side bar are mashed together in the image. It does not make your README look professional.

2020-08-17 17:17 UTC, krys2fa commented on index.html
> -    <title>Document</title>
- [x] [REQUIRED] There is no need to have the meta tags and title taken out. They help search engines understand your page. Please put them back and replace the title with a more suitable one. Eg: Youtube Clone.

2020-08-17 17:17 UTC, krys2fa commented on index.html
> +                 <p style="display: inline-block;">REPLY</p>
- [x] [REQUIRED] Inline styling are frowned upon. They are considered [bad CSS practice](https://speckyboy.com/good-bad-css-practices). Please move all inline styles in this and all other sections to an external stylesheet.

2020-08-17 17:17 UTC, krys2fa commented on style.css
> +}
- [x] [REQUIRED] Kindly remove the duplicate selector for this rule.

2020-08-17 17:17 UTC, krys2fa commented on style.css
> +}
- [x] [REQUIRED] This rule is empty and not necessary. Kindly remove this.

2020-08-18 07:48 UTC, GzimAsani commented
> ## Awesome work @GzimAsani and @Rayan84 
> Your project displays good use of CSS classes and GitHub Flow. 
> 
> Just a few more adjustments to improve and complete the project. Please find them listed below.
> 
> ### Status: Changes Required 
> * [ ]  [REQUIRED] The Pull Request should have a meaningful title. Something like in the image below.
>   ![Screen Shot 2020-07-09 at 4 37 08 PM](https://user-images.githubusercontent.com/18187039/90422808-e9cfe700-e0aa-11ea-923f-05e7c710572e.png)
> * [ ]  [REQUIRED] The search icon is not positioned correctly in the search input. This is what your page shows:
>   ![Screen Shot 2020-08-17 at 5 04 52 PM](https://user-images.githubusercontent.com/18187039/90423405-ea1cb200-e0ab-11ea-8e82-caab1c6a2486.png)
> * [ ]  [REQUIRED] The `Up Next` title and `Autoplay` icons are missing in your side bar.
>   This is what is present in the original:
> 
> <img alt="Screen Shot 2020-08-17 at 5 10 39 PM" width="382" src="https://user-images.githubusercontent.com/18187039/90423796-a2e2f100-e0ac-11ea-8d84-02d1846d4c31.png">
> 
> * [ ]  [REQUIRED ] The footer is missing from your page. It should look like this:
> 
> <img alt="Screen Shot 2020-08-17 at 5 13 37 PM" width="993" src="https://user-images.githubusercontent.com/18187039/90424118-1edd3900-e0ad-11ea-9381-7f11e210e1ff.png">
> 
> * [ ]  [REQUIRED]  Your project should match the appearance of [this archived youtube video player page. ](http://archive.vn/Bss88)
> 
> **NB:** The web page was reviewed at a screen size of **1440px.** Kindly state the screen size the project was built at if the page displays better at that size.
> 
> Happy Coding  
> 
> ###### You can contact me on slack (Chris Amanor) for any clarification.

Hello Christopher, thank you so much for you detailed review. We appreciate your time. We will check our errors and after fixing them we would request another review.

2020-08-18 13:35 UTC, GzimAsani commented
Kindly reminding that the project was build in 1366px.

2020-08-18 14:05 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @GzimAsani @Rayan84** 
Good job with your new submission for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [x] In the HTML file, remove the repeated link to the style.css file
- [x] Don't repeat yourself, group selectors with the same style definition: https://www.w3schools.in/css3/group-selector/

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-18 14:05 UTC, andresporras3423 commented on style.css
> +  }
Group selectors with the same style definition

2020-08-18 14:05 UTC, andresporras3423 commented on style.css
> +  }
Group selectors

2020-08-18 14:05 UTC, andresporras3423 commented on index.html
> +    <link rel="stylesheet" href="style.css">
remove repeated link

2020-08-18 16:26 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @GzimAsani and @Rayan84 :wave: 

Thank you for making all of the required changes from the last TSE, your project is approved, congratulations :clap: :clap: :clap: 

You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-19 08:25 UTC, merged